// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AutomovilDbContext))]
    partial class AutomovilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Automovil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fabricacion")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroChasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroMotor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Automovil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Negro",
                            Fabricacion = 2020,
                            Marca = "Toyota",
                            Modelo = "Yaris",
                            NumeroChasis = "CHASIS12345",
                            NumeroMotor = "MOTOR12345"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Rojo",
                            Fabricacion = 2019,
                            Marca = "Ford",
                            Modelo = "Mustang",
                            NumeroChasis = "CHASIS67890",
                            NumeroMotor = "MOTOR67890"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Negro",
                            Fabricacion = 2021,
                            Marca = "Chevrolet",
                            Modelo = "Cruze",
                            NumeroChasis = "CHASIS11223",
                            NumeroMotor = "MOTOR11223"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Gris",
                            Fabricacion = 2022,
                            Marca = "Honda",
                            Modelo = "Civic",
                            NumeroChasis = "CHASIS44556",
                            NumeroMotor = "MOTOR44556"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Azul",
                            Fabricacion = 2018,
                            Marca = "Volkswagen",
                            Modelo = "Golf",
                            NumeroChasis = "CHASIS77889",
                            NumeroMotor = "MOTOR77889"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Blanco",
                            Fabricacion = 2023,
                            Marca = "Nissan",
                            Modelo = "Sentra",
                            NumeroChasis = "CHASIS99001",
                            NumeroMotor = "MOTOR99001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
